### ISSUE TITLE
How to add this spinner in the datagrid table 

### ISSUE THREAD

**Issue by vishalkr058** [vikas62081/YT#13]
I am using reactjs material UI datagrid table to fetch API show data in the table but it has deafult "No Rows" loader while waiting to fetch data. So, I want to add this kind of spinner to my table until the data load in the table. I tried to implement this example from youtube but couldn't able to succeed.

If you could post example on to implement spinner in the reactjs material ui datagrid table ?

**Comment by vikas62081** [comment]
To show a overlay while fetching api data on table pass property loading=true, once data fetched from api set loading=false.
Have a look on below example

import React, { useEffect, useState } from "react";
import { DataGrid } from "@mui/x-data-grid";

const columns = [
  { field: "id", headerName: "ID" },
  {
    field: "title",
    headerName: "title",
    width: 150,
    editable: true
  },
  {
    field: "body",
    headerName: "Message",
    width: 350,
    editable: true
  }
];

export default function DataGridDemo() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    fetch("https://jsonplaceholder.typicode.com/posts")
      .then((resp) => resp.json())
      .then((resp) => {
        setData(resp);
        setLoading(false);
      });
  }, []);
  return (
    <div style={{ height: 400, width: "100%" }}>
      <DataGrid
        rows={data}
        columns={columns}
        loading={loading}
      />
    </div>
  );
}

**Comment by vishalkr058** [comment]
Hi @vikas62081 , Thanks for the response. I am able to implement using this method, and it's working fine for me.

**Comment by julix-unity** [comment]
In case anyone else needs to see it - here it is formatted

```JavaScript
import React, { useEffect, useState } from "react";
import { DataGrid } from "@mui/x-data-grid";

const columns = [
    { field: "id", headerName: "ID" },
    {
        field: "title",
        headerName: "title",
        width: 150,
        editable: true
    },
    {
        field: "body",
        headerName: "Message",
        width: 350,
        editable: true
    }
];

export default function DataGridDemo() {
    const [data, setData] = useState([]);
    const [loading, setLoading] = useState(true);
    useEffect(() => {
        fetch("https://jsonplaceholder.typicode.com/posts")
            .then((resp) => resp.json())
            .then((resp) => {
                setData(resp);
                setLoading(false);
            });
    }, []);
    return (<div style={{ height: 400, width: "100%" }}>);
}
```
